### ISSUE TITLE
Out of Funds, the Bank/Pool is empty

### ISSUE THREAD

**Issue by ZeroChills** [vsnation/beam_butler#1]
The Beam Butler is stating that there isn't anymore $BEAM left and that it needs to be refilled. It does say to refill using a /tip command.. However, I don't even know how to generate $Beam let alone filling this on my own?  Cheers!  Also, plz let me learn more than than the stock two channels on discord allow... I did a search for "Vsnation beampay" as I stated I would so IDK what's next, just trying to wrap my head around BEAM that's all...

**Comment by ZeroChills** [comment]
Dumb

**Comment by vsnation** [comment]
Hi, sorry for so long delay. Contact me on Telegram, I will solve your issue.
